2019-07-08 23:09:57,861 ERROR: Exception on /index [GET] [in /home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/lomolo/Projects/microblog/app/routes.py", line 36, in index
    False
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 496, in paginate
    items = self.limit(per_page).offset((page - 1) * per_page).all()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3168, in all
    return list(self)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3320, in __iter__
    context = self._compile_context()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3876, in _compile_context
    context.statement = self._simple_statement(context)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3969, in _simple_statement
    **self._select_args
  File "<string>", line 2, in select
  File "<string>", line 2, in __init__
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/util/deprecations.py", line 130, in warned
    return fn(*args, **kwargs)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/selectable.py", line 2961, in __init__
    GenerativeSelect.__init__(self, **kwargs)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/selectable.py", line 2152, in __init__
    self._offset_clause = _offset_or_limit_clause(offset)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/selectable.py", line 95, in _offset_or_limit_clause
    value = util.asint(element)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 1116, in asint
    return int(value)
ValueError: invalid literal for int() with base 10: ''
2019-07-08 23:11:46,037 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:51]
2019-07-08 23:12:31,741 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:51]
2019-07-08 23:23:04,443 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:51]
